name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Rust
      run: cargo build --verbose
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.4.0
    - name: Build Wasm
      run: wasm-pack build --target web
    - name: Build NodeJS
      run: npm install --prefix www
